### ISSUE TITLE
Double loading on first run :(

### ISSUE THREAD

**Issue by goblin776655** [p1atdev/stable-diffusion-webui-blip2-captioner#1]
When I first clicked to Interrogate I see 2 loading and after it loaded it generate text 2 times :(
Loading coco model...
Loading coco model...
Position interpolate from 16x16 to 26x26
Position interpolate from 16x16 to 26x26
Model coco loaded
Generating captions...
a man in front of many women dressed in military uniforms
Model coco loaded
Generating captions...
kim yong bin poses for a photograph with women wearing hats

If unload model and click again - all fine!
It took X2 more time on first click :((

**Comment by p1atdev** [comment]
The interrogation starts automatically when an image is selected, but it seems that the model is loaded twice because the button can still be pressed during this time.
In the latest version, the auto-interrogation has been disabled to prevent accidental operation.

**Comment by goblin776655** [comment]
> The interrogation starts automatically when an image is selected, but it seems that the model is loaded twice because the button can still be pressed during this time. In the latest version, the auto-interrogation has been disabled to prevent accidental operation.


Yes, it looks like this is the reason, double load.
Thanks.
